language: node_js
node_js: lts/*

before_script:
  - npm install -g gulp-cli parcel-bundler eslint

script:
  - yarn lint
  # - yarn travis
  - ls

deploy:
  provider: pages
  skip_cleanup: true
  # travis: skip cleanup depreciated, don't use
  # also travis: YOU DIDN'T SAY SKIP CLEANUP, I'M SKIPPING IT
  github_token: $GITHUB_TOKEN
  on:
    all_branches: true
