language: node_js
node_js: lts/*

script:
  - yarn lint
  - yarn build
  - ls
  # move everything in out up to root?
  - cp -r ./build/* .

deploy:
  provider: pages
  skip_cleanup: true
  # travis: skip cleanup depreciated, don't use
  # also travis: YOU DIDN'T SAY SKIP CLEANUP, I'M SKIPPING IT
  github_token: $GITHUB_TOKEN
  on:
    all_branches: true
